# Generated by Django 4.0 on 2021-12-28 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
