# Generated by Django 4.0 on 2021-12-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificate_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
